import type {
  EsporteCompetition,
  EsporteGame,
  EsporteKnockoutBracket,
  EsporteSport,
  EsporteStanding,
  EsporteTeam,
  EsporteTeamStats,
} from "./types";

export const MOCK_SPORTS: EsporteSport[] = [
  {
    id: "sport-futsal-m",
    slug: "futsal-masculino",
    name: "Futsal",
    gender: "masculino",
    icon: "⚽",
  },
  {
    id: "sport-futsal-f",
    slug: "futsal-feminino",
    name: "Futsal",
    gender: "feminino",
    icon: "⚽",
  },
  {
    id: "sport-basquete-m",
    slug: "basquete-masculino",
    name: "Basquete",
    gender: "masculino",
    icon: "🏀",
  },
  {
    id: "sport-basquete-f",
    slug: "basquete-feminino",
    name: "Basquete",
    gender: "feminino",
    icon: "🏀",
  },
  {
    id: "sport-volei-m",
    slug: "volei-masculino",
    name: "Vôlei",
    gender: "masculino",
    icon: "🏐",
  },
  {
    id: "sport-volei-f",
    slug: "volei-feminino",
    name: "Vôlei",
    gender: "feminino",
    icon: "🏐",
  },
];

export const MOCK_TEAMS: EsporteTeam[] = [
  { id: "team-link", name: "Link School", shortName: "Link", logoUrl: null, color: "#006b3f" },
  { id: "team-espm", name: "ESPM", shortName: "ESPM", logoUrl: null, color: "#c41e3a" },
  { id: "team-fgv", name: "FGV", shortName: "FGV", logoUrl: null, color: "#003366" },
  { id: "team-insper", name: "Insper", shortName: "Insper", logoUrl: null, color: "#1a1a2e" },
  { id: "team-mack", name: "Mackenzie", shortName: "Mack", logoUrl: null, color: "#8b0000" },
  { id: "team-puc", name: "PUC-SP", shortName: "PUC", logoUrl: null, color: "#003087" },
  { id: "team-fea", name: "FEA-USP", shortName: "FEA", logoUrl: null, color: "#ffd700" },
  { id: "team-poliusp", name: "Poli-USP", shortName: "Poli", logoUrl: null, color: "#004d40" },
];

export const MOCK_COMPETITIONS: EsporteCompetition[] = [
  {
    id: "comp-futsal-m",
    sportId: "sport-futsal-m",
    name: "NDU Futsal Masculino",
    season: "2026",
    hasKnockout: true,
  },
  {
    id: "comp-futsal-f",
    sportId: "sport-futsal-f",
    name: "NDU Futsal Feminino",
    season: "2026",
    hasKnockout: true,
  },
  {
    id: "comp-basquete-m",
    sportId: "sport-basquete-m",
    name: "NDU Basquete Masculino",
    season: "2026",
    hasKnockout: true,
  },
  {
    id: "comp-basquete-f",
    sportId: "sport-basquete-f",
    name: "NDU Basquete Feminino",
    season: "2026",
    hasKnockout: false,
  },
  {
    id: "comp-volei-m",
    sportId: "sport-volei-m",
    name: "NDU Vôlei Masculino",
    season: "2026",
    hasKnockout: true,
  },
  {
    id: "comp-volei-f",
    sportId: "sport-volei-f",
    name: "NDU Vôlei Feminino",
    season: "2026",
    hasKnockout: false,
  },
];

export const MOCK_GAMES: EsporteGame[] = [
  {
    id: "game-1",
    competitionId: "comp-futsal-m",
    homeTeamId: "team-link",
    awayTeamId: "team-espm",
    homeScore: null,
    awayScore: null,
    scheduledAt: "2026-06-24T19:00:00-03:00",
    venue: "Ginásio NDU",
    status: "scheduled",
    round: "Rodada 8",
  },
  {
    id: "game-2",
    competitionId: "comp-futsal-m",
    homeTeamId: "team-fgv",
    awayTeamId: "team-insper",
    homeScore: null,
    awayScore: null,
    scheduledAt: "2026-06-24T20:30:00-03:00",
    venue: "Ginásio NDU",
    status: "scheduled",
    round: "Rodada 8",
  },
  {
    id: "game-3",
    competitionId: "comp-basquete-m",
    homeTeamId: "team-mack",
    awayTeamId: "team-puc",
    homeScore: null,
    awayScore: null,
    scheduledAt: "2026-06-25T18:00:00-03:00",
    venue: "Quadra Mackenzie",
    status: "scheduled",
    round: "Rodada 5",
  },
  {
    id: "game-4",
    competitionId: "comp-volei-m",
    homeTeamId: "team-fea",
    awayTeamId: "team-poliusp",
    homeScore: null,
    awayScore: null,
    scheduledAt: "2026-06-25T19:30:00-03:00",
    venue: "Ginásio USP",
    status: "scheduled",
    round: "Rodada 6",
  },
  {
    id: "game-5",
    competitionId: "comp-futsal-f",
    homeTeamId: "team-espm",
    awayTeamId: "team-fgv",
    homeScore: null,
    awayScore: null,
    scheduledAt: "2026-06-26T19:00:00-03:00",
    venue: "Ginásio ESPM",
    status: "scheduled",
    round: "Rodada 7",
  },
  {
    id: "game-6",
    competitionId: "comp-futsal-m",
    homeTeamId: "team-link",
    awayTeamId: "team-espm",
    homeScore: 3,
    awayScore: 1,
    scheduledAt: "2026-06-20T19:00:00-03:00",
    venue: "Ginásio NDU",
    status: "finished",
    round: "Rodada 7",
  },
  {
    id: "game-7",
    competitionId: "comp-futsal-m",
    homeTeamId: "team-fgv",
    awayTeamId: "team-mack",
    homeScore: 2,
    awayScore: 2,
    scheduledAt: "2026-06-19T20:00:00-03:00",
    venue: "Ginásio FGV",
    status: "finished",
    round: "Rodada 7",
  },
  {
    id: "game-8",
    competitionId: "comp-basquete-m",
    homeTeamId: "team-insper",
    awayTeamId: "team-link",
    homeScore: 78,
    awayScore: 65,
    scheduledAt: "2026-06-18T18:30:00-03:00",
    venue: "Quadra Insper",
    status: "finished",
    round: "Rodada 4",
  },
  {
    id: "game-9",
    competitionId: "comp-volei-m",
    homeTeamId: "team-puc",
    awayTeamId: "team-espm",
    homeScore: 3,
    awayScore: 0,
    scheduledAt: "2026-06-17T19:00:00-03:00",
    venue: "Ginásio PUC",
    status: "finished",
    round: "Rodada 5",
  },
  {
    id: "game-10",
    competitionId: "comp-futsal-m",
    homeTeamId: "team-puc",
    awayTeamId: "team-fea",
    homeScore: 1,
    awayScore: 0,
    scheduledAt: "2026-06-24T21:00:00-03:00",
    venue: "Ginásio PUC",
    status: "live",
    round: "Rodada 8",
  },
  {
    id: "game-11",
    competitionId: "comp-futsal-f",
    homeTeamId: "team-link",
    awayTeamId: "team-mack",
    homeScore: 4,
    awayScore: 2,
    scheduledAt: "2026-06-15T19:00:00-03:00",
    venue: "Ginásio Link",
    status: "finished",
    round: "Rodada 6",
  },
  {
    id: "game-12",
    competitionId: "comp-basquete-f",
    homeTeamId: "team-fgv",
    awayTeamId: "team-espm",
    homeScore: 55,
    awayScore: 48,
    scheduledAt: "2026-06-14T17:00:00-03:00",
    venue: "Quadra FGV",
    status: "finished",
    round: "Rodada 3",
  },
];

export const MOCK_STANDINGS: EsporteStanding[] = [
  { position: 1, teamId: "team-link", competitionId: "comp-futsal-m", points: 21, gamesPlayed: 7, wins: 7, draws: 0, losses: 0, goalsFor: 22, goalsAgainst: 8 },
  { position: 2, teamId: "team-fgv", competitionId: "comp-futsal-m", points: 16, gamesPlayed: 7, wins: 5, draws: 1, losses: 1, goalsFor: 18, goalsAgainst: 10 },
  { position: 3, teamId: "team-espm", competitionId: "comp-futsal-m", points: 13, gamesPlayed: 7, wins: 4, draws: 1, losses: 2, goalsFor: 15, goalsAgainst: 12 },
  { position: 4, teamId: "team-insper", competitionId: "comp-futsal-m", points: 10, gamesPlayed: 7, wins: 3, draws: 1, losses: 3, goalsFor: 12, goalsAgainst: 14 },
  { position: 5, teamId: "team-mack", competitionId: "comp-futsal-m", points: 7, gamesPlayed: 7, wins: 2, draws: 1, losses: 4, goalsFor: 10, goalsAgainst: 15 },
  { position: 6, teamId: "team-puc", competitionId: "comp-futsal-m", points: 6, gamesPlayed: 7, wins: 2, draws: 0, losses: 5, goalsFor: 9, goalsAgainst: 16 },
  { position: 7, teamId: "team-fea", competitionId: "comp-futsal-m", points: 4, gamesPlayed: 7, wins: 1, draws: 1, losses: 5, goalsFor: 8, goalsAgainst: 17 },
  { position: 8, teamId: "team-poliusp", competitionId: "comp-futsal-m", points: 3, gamesPlayed: 7, wins: 1, draws: 0, losses: 6, goalsFor: 7, goalsAgainst: 19 },

  { position: 1, teamId: "team-espm", competitionId: "comp-futsal-f", points: 18, gamesPlayed: 6, wins: 6, draws: 0, losses: 0, goalsFor: 20, goalsAgainst: 5 },
  { position: 2, teamId: "team-link", competitionId: "comp-futsal-f", points: 12, gamesPlayed: 6, wins: 4, draws: 0, losses: 2, goalsFor: 16, goalsAgainst: 10 },
  { position: 3, teamId: "team-fgv", competitionId: "comp-futsal-f", points: 9, gamesPlayed: 6, wins: 3, draws: 0, losses: 3, goalsFor: 12, goalsAgainst: 11 },
  { position: 4, teamId: "team-mack", competitionId: "comp-futsal-f", points: 6, gamesPlayed: 6, wins: 2, draws: 0, losses: 4, goalsFor: 9, goalsAgainst: 14 },

  { position: 1, teamId: "team-insper", competitionId: "comp-basquete-m", points: 12, gamesPlayed: 4, wins: 4, draws: 0, losses: 0, goalsFor: 312, goalsAgainst: 260 },
  { position: 2, teamId: "team-mack", competitionId: "comp-basquete-m", points: 9, gamesPlayed: 4, wins: 3, draws: 0, losses: 1, goalsFor: 295, goalsAgainst: 275 },
  { position: 3, teamId: "team-link", competitionId: "comp-basquete-m", points: 6, gamesPlayed: 4, wins: 2, draws: 0, losses: 2, goalsFor: 280, goalsAgainst: 285 },
  { position: 4, teamId: "team-puc", competitionId: "comp-basquete-m", points: 3, gamesPlayed: 4, wins: 1, draws: 0, losses: 3, goalsFor: 265, goalsAgainst: 292 },

  { position: 1, teamId: "team-puc", competitionId: "comp-volei-m", points: 15, gamesPlayed: 5, wins: 5, draws: 0, losses: 0, goalsFor: 15, goalsAgainst: 3 },
  { position: 2, teamId: "team-fea", competitionId: "comp-volei-m", points: 9, gamesPlayed: 5, wins: 3, draws: 0, losses: 2, goalsFor: 11, goalsAgainst: 8 },
  { position: 3, teamId: "team-poliusp", competitionId: "comp-volei-m", points: 6, gamesPlayed: 5, wins: 2, draws: 0, losses: 3, goalsFor: 8, goalsAgainst: 11 },
  { position: 4, teamId: "team-espm", competitionId: "comp-volei-m", points: 3, gamesPlayed: 5, wins: 1, draws: 0, losses: 4, goalsFor: 5, goalsAgainst: 12 },
];

export const MOCK_KNOCKOUT_BRACKETS: Record<string, EsporteKnockoutBracket> = {
  "comp-futsal-m": {
    competitionId: "comp-futsal-m",
    rounds: [
      {
        phase: "quartas",
        label: "Quartas de Final",
        matches: [
          { id: "ko-q1", homeTeamId: "team-link", awayTeamId: "team-puc", homeScore: 4, awayScore: 1, status: "finished" },
          { id: "ko-q2", homeTeamId: "team-fgv", awayTeamId: "team-mack", homeScore: 3, awayScore: 2, status: "finished" },
          { id: "ko-q3", homeTeamId: "team-espm", awayTeamId: "team-fea", homeScore: 2, awayScore: 0, status: "finished" },
          { id: "ko-q4", homeTeamId: "team-insper", awayTeamId: "team-poliusp", homeScore: null, awayScore: null, status: "scheduled" },
        ],
      },
      {
        phase: "semifinal",
        label: "Semifinal",
        matches: [
          { id: "ko-s1", homeTeamId: "team-link", awayTeamId: "team-fgv", homeScore: null, awayScore: null, status: "scheduled" },
          { id: "ko-s2", homeTeamId: "team-espm", awayTeamId: null, homeScore: null, awayScore: null, status: "scheduled" },
        ],
      },
      {
        phase: "final",
        label: "Final",
        matches: [
          { id: "ko-f1", homeTeamId: null, awayTeamId: null, homeScore: null, awayScore: null, status: "scheduled" },
        ],
      },
    ],
  },
  "comp-basquete-m": {
    competitionId: "comp-basquete-m",
    rounds: [
      {
        phase: "quartas",
        label: "Quartas de Final",
        matches: [
          { id: "ko-bq1", homeTeamId: "team-insper", awayTeamId: "team-puc", homeScore: null, awayScore: null, status: "scheduled" },
          { id: "ko-bq2", homeTeamId: "team-mack", awayTeamId: "team-link", homeScore: null, awayScore: null, status: "scheduled" },
        ],
      },
      {
        phase: "semifinal",
        label: "Semifinal",
        matches: [
          { id: "ko-bs1", homeTeamId: null, awayTeamId: null, homeScore: null, awayScore: null, status: "scheduled" },
          { id: "ko-bs2", homeTeamId: null, awayTeamId: null, homeScore: null, awayScore: null, status: "scheduled" },
        ],
      },
      {
        phase: "final",
        label: "Final",
        matches: [
          { id: "ko-bf1", homeTeamId: null, awayTeamId: null, homeScore: null, awayScore: null, status: "scheduled" },
        ],
      },
    ],
  },
};

export const MOCK_TEAM_STATS: EsporteTeamStats[] = MOCK_STANDINGS.map((s) => ({
  teamId: s.teamId,
  competitionId: s.competitionId,
  gamesPlayed: s.gamesPlayed,
  wins: s.wins,
  draws: s.draws,
  losses: s.losses,
  goalsFor: s.goalsFor,
  goalsAgainst: s.goalsAgainst,
}));
